spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_spb3?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  mail:
    host: smtp.163.com
    username: sherly_cs_sh@163.com
    password: DBSCPMWLJTJPQSVK
    properties:
      from: "Study-SPB3 <sherly_cs_sh@163.com>"

  data:
    redis:
      database: 0
      host: localhost
      port: 6379